# Generated by Django 4.1.3 on 2022-11-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('full_video_path', models.CharField(max_length=50)),
                ('full_audio_path', models.CharField(max_length=50)),
                ('full_conversation_path', models.TextField()),
            ],
            options={
                'db_table': 'chat_session',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('active_users_number', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'emotion',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('stressed', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.company')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='StressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('stressedUsers', models.IntegerField()),
            ],
            options={
                'db_table': 'stress_record',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_question', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.company')),
            ],
            options={
                'db_table': 'wheel',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('wheel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.wheel')),
            ],
            options={
                'db_table': 'prize',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.company')),
            ],
            options={
                'db_table': 'employers',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.topic')),
            ],
            options={
                'db_table': 'employee_topic',
            },
        ),
        migrations.CreateModel(
            name='EmployeePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('prize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.prize')),
            ],
            options={
                'db_table': 'employee_prize',
            },
        ),
        migrations.CreateModel(
            name='ChatSessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('video_url', models.CharField(max_length=50)),
                ('audio_url', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('chatbot_answer', models.TextField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.chatsession')),
            ],
            options={
                'db_table': 'chat_session_message',
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='first_prevailing_emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_prevailing_emotion', to='employee.emotion'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='second_prevailing_emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_prevailing_emotion', to='employee.emotion'),
        ),
    ]
