# Generated by Django 4.1.3 on 2022-11-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='stressed',
            field=models.BooleanField(default=False),
        ),
    ]
