# Generated by Django 4.1.3 on 2022-11-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_password_employer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
