# Generated by Django 4.1.3 on 2022-11-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_stressed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
