# Generated by Django 4.1.3 on 2022-11-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
