# Generated by Django 4.1.3 on 2022-11-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employer_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stressedUsers', models.IntegerField()),
            ],
        ),
    ]
