# Generated by Django 4.1.3 on 2022-11-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_stressrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stressrecord',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
